### ISSUE TITLE
[Django] Plugin assumes app is in current directory

### ISSUE THREAD

**Issue by brettdh** [logandk/serverless-wsgi#24] opened 2017-08-17 15:16 UTC
I'm using serverless to deploy a Django (REST Framework) API as an AWS Lambda function, and I'm also going to be deploying other Lambda functions that are not WSGI apps. I have this all in one repo right now, with `serverless.yml` alongside `api`, where `api` is the Django project directory.

Thus, I set `custom.wsgi.app: api.api.wsgi.application`. This allows the WSGI handler to find my app just fine, but when the app runs, it appears that the working directory is still the root of my repo, rather than the root of the Django app, because I get an import error on `api.settings`. I get the same error message when deploying the endpoint to AWS and testing there.

Sorry if this is misfiled; I'm not sure if this is a question about Django, serverless, or serverless-wsgi, as I'm new to all of them. :) Is there a way to make sure the function that runs my Django app from a working directory other than where `serverless.yml` lives? Is that up to serverless or serverless-wsgi, or Django?

**Comment by logandk** [comment] 2017-08-17 18:04
@brettdh Does it work if you set `custom.wsgi.app: api/api.wsgi.application`?

Alternatively, could you please provide a simple reproduction setup? It sounds like this may be a Python package import issue, rather than something specific to this plugin, but I can't tell from your description alone

**Comment by brettdh** [comment] 2017-08-17 18:07
Nope; same error.

I'll take a moment to make a repro project.

**Comment by brettdh** [comment] 2017-08-17 18:43
Here it is: https://github.com/brettdh/serverless-wsgi-django-import-error

**Comment by brettdh** [comment] 2017-08-17 18:55
Let me put the obvious out there: I could put `serverless.yml` in the Django project dir (`api/`), have another one for other lambda functions, and run `sis deploy` in multiple places - but of course that's not ideal.

**Comment by logandk** [comment] 2017-08-17 19:03
Thanks for putting this together, I'll take a look - and I agree that we should be able to support both cases

**Comment by brettdh** [comment] 2017-08-17 19:48
Found another possible workaround:
https://github.com/brettdh/serverless-wsgi-django-import-error/tree/package
See also explanation here:
https://github.com/brettdh/serverless-wsgi-django-import-error/commit/1ba07d89d95486eecf4049523ad95f53485c18db

**Comment by brettdh** [comment] 2017-08-18 14:30
Shoot, it works for `sis wsgi serve`, but when I `sis deploy`, `requirements-pipenv.txt` can't be found in the `.serverless` directory. That seems like an issue with `serverless-python-requirements` though.

**Comment by brettdh** [comment] 2017-08-18 15:03
Using `serverless-wsgi` for packaging instead of `serverless-python-requirements` avoids that issue though, but then the deployed function can't import `api.wsgi`. :|

**Comment by brettdh** [comment] 2017-08-18 15:43
K, changed to using a script to produce `requirements.txt` with the pipenv stuff and the local stuff. Got an error about link collision with the local `api` dir; moved it to `src/api`, and `sis deploy` now works.

I've gotten to an issue with Amazon Linux not having sqlite3 dev lib installed and thus Django fails to `import sqlite3`, but I wasn't planning to continue using sqlite3 on lambda anyway; it was just for quick testing. So I think I've worked around this issue now, but I won't know for sure until I can get that JSON response out of it. :) Will report back soon.

**Comment by brettdh** [comment] 2017-08-18 15:46
Left out an important detail above: since the new error comes (I assume) from within Django, this tells me that my lambda function successfully found my Django app.

**Comment by logandk** [comment] 2017-08-20 20:15
@brettdh Thanks for the notes. I tried out your repro project, and it appears to me that the problem is that the `api` directory is not a package (no `__init__.py`), causing the import to fail. Adding `__init__.py` doesn't work, however, due to the way Django expects the project to be structured. The solution is to add the `api` directory to `PYTHONPATH`, so that it will be searched when importing packages.

Could you give the `master` a try and see if it works? (You can checkout the `serverless-wsgi` repo locally, make it your cwd, run `npm link` and then run `npm link serverless-wsgi` inside the directory of your serverless project).

**Comment by brettdh** [comment] 2017-08-21 13:04
Installed `master`; encountered the same error (plus a bit):

https://github.com/brettdh/serverless-wsgi-django-import-error/commit/6765f44745807f28bc86789e1f366a217f7f2735

**Comment by logandk** [comment] 2017-08-21 19:13
Looks like I didn't test properly on Python 3.6. It was relying on `ImportError` which are superseded by `ModuleNotFoundError` on 3.6 in some cases. I decided to drop the previous approach of importing subdirectories as packages, and add the subdirectory to the search path by default. This simplifies things and should fix the issue you were seeing.

**Comment by brettdh** [comment] 2017-08-21 19:27
LGTM locally as well on my test project. Thanks!

**Comment by brettdh** [comment] 2017-08-22 19:07
Thanks again for fixing this quickly. I've pinned the current commit from `master` for now; I assume you'll close this issue once 1.3.0 is released?

**Comment by logandk** [comment] 2017-08-29 20:06
I'm closing this and releasing 1.3.0 now

**Closed by logandk** 2017-08-29 20:06 UTC
