### ISSUE TITLE
Serverless.yml settings for django graphql

### ISSUE THREAD

**Issue by chrisstetter** [logandk/serverless-wsgi#62] opened 2018-06-09 08:27 UTC
Hi,

I am trying to deploy a django graphql api to aws. I have exactly followed [this](http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/) example. In addition I have added the aws endpoint given after deploying to aws in allowed_hosts of the settings.py. Anyway, I always get "{"message": "Internal server error"}" independent of which view I am trying to access. According to [serverless-wsgi](https://github.com/logandk/serverless-wsgi) the app under custom should be set to "cookbook.wsgi.application". But do I need to adjust the prefix of wsgi.handler under functions? Here it is "api", whereas in the official serverless blog post "[Build a Python REST API with Serverless, Lambda, and DynamoDB](https://serverless.com/blog/flask-python-rest-api-serverless-lambda-dynamodb/)" it is "app". Both are flask, to what should it be adjusted in this django case?

Currently my serverless.yml looks like this:
```
service: cookbook

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: cookbook.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```
Cheers

**Comment by logandk** [comment] 2018-06-11 08:04
Hi, I would suggest that you first check that everything is working using `sls wsgi serve` and also make sure to check the logs of the lambda function to diagnose the error

**Comment by chrisstetter** [comment] 2018-06-11 08:47
Doing `sls logs -f app` gave me back the following. Installing werkzeug and deploying again did not resolve the issue, still getting the No module named 'werkzeug' message. `sls wsgi serve` works just as expected.

```
START RequestId: 7aca2bb6-6b22-11e8-9ed9-cda659034775 Version: $LATEST
Unable to import module 'wsgi': No module named 'werkzeug'

END RequestId: 7aca2bb6-6b22-11e8-9ed9-cda659034775
REPORT RequestId: 7aca2bb6-6b22-11e8-9ed9-cda659034775  Duration: 0.50 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 22 MB

START RequestId: 7ea0611a-6b22-11e8-8763-f599d843a141 Version: $LATEST
Unable to import module 'wsgi': No module named 'werkzeug'

END RequestId: 7ea0611a-6b22-11e8-8763-f599d843a141
REPORT RequestId: 7ea0611a-6b22-11e8-8763-f599d843a141  Duration: 0.37 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 22 MB

START RequestId: cc4d05cb-6b22-11e8-a307-258b9a479e3f Version: $LATEST
Unable to import module 'wsgi': No module named 'werkzeug'

END RequestId: cc4d05cb-6b22-11e8-a307-258b9a479e3f
REPORT RequestId: cc4d05cb-6b22-11e8-a307-258b9a479e3f  Duration: 2.09 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 23 MB

START RequestId: bd3e3c67-6b23-11e8-97ea-c7e4e4aaf386 Version: $LATEST
Unable to import module 'wsgi': No module named 'werkzeug'

END RequestId: bd3e3c67-6b23-11e8-97ea-c7e4e4aaf386
REPORT RequestId: bd3e3c67-6b23-11e8-97ea-c7e4e4aaf386  Duration: 0.45 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 22 MB

START RequestId: bd899680-6b26-11e8-a8a5-016158fa097c Version: $LATEST
Unable to import module 'cookbook/wsgi': No module named '_sqlite3'

END RequestId: bd899680-6b26-11e8-a8a5-016158fa097c
REPORT RequestId: bd899680-6b26-11e8-a8a5-016158fa097c  Duration: 0.55 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 61 MB

START RequestId: c92d524e-6b26-11e8-97ea-c7e4e4aaf386 Version: $LATEST
Unable to import module 'cookbook/wsgi': No module named '_sqlite3'

END RequestId: c92d524e-6b26-11e8-97ea-c7e4e4aaf386
REPORT RequestId: c92d524e-6b26-11e8-97ea-c7e4e4aaf386  Duration: 0.59 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 62 MB

```

**Comment by logandk** [comment] 2018-06-11 18:11
Ok, this looks like it's related to packaging, and since you're using `serverless-python-requirements` for that, you'll need to open an issue on that project instead.

**Comment by chrisstetter** [comment] 2018-06-12 08:49
I have removed the lambda function and pip installed all the packages again, and then re-deployed. Now the issue is the following:

```
START RequestId: ba751e83-6e1b-11e8-9558-b9437389f736 Version: $LATEST
Syntax error in module 'wsgi': invalid syntax (_base.py, line 357)

END RequestId: ba751e83-6e1b-11e8-9558-b9437389f736
REPORT RequestId: ba751e83-6e1b-11e8-9558-b9437389f736  Duration: 0.78 ms       Billed Duration: 100 ms         Memory Size: 1024 MB    Max Memory Used: 49 MB
```

I kind of have the feeling this is related to the configuration issue of django apps in the serverless.yml as mentioned in the initial post. Or am I wrong?

**Comment by logandk** [comment] 2018-06-15 13:28
Right, this error indicates something different. Could you put together a complete setup for reproducing this? (serverless config + your code/requirements file)

**Comment by chrisstetter** [comment] 2018-06-18 08:59
[cookbook.zip](https://github.com/logandk/serverless-wsgi/files/2110618/cookbook.zip)
I  hope that is all you need.

**Comment by logandk** [comment] 2018-07-03 20:08
I finally had a chance to try this out. You have `futures` listed in your requirements, which doesn't work on Python 3 (the futures package is a backport for Python 2). Removing this from requirements fixes the issue.

You'll then get an error importing `_sqlite3` due to your django config. If you really want to use sqlite on Lambda, you'll need to figure that out, but I'm closing this issue since that's outside the scope of this plugin.

**Closed by logandk** 2018-07-03 20:08 UTC
Labels: question
