### ISSUE TITLE
Multiple cookie headers no longer working as expected

### ISSUE THREAD

**Issue by grvhi** [logandk/serverless-wsgi#70] opened 2018-08-01 13:49 UTC
I'm not certain of the best way to debug this problem, but my WSGI app (Falcon, in this case) sets multiple `Set-Cookie` headers on certain responses and the cookies are correctly set when running locally. 

However, when running the same code after deploying to Lambda (using serverless-wsgi), my application works entirely as expected with the notable exception that all responses only ever contain a single `set-cookie` header with a single cookie value in them. 

This problem is evident in Chrome and Safari (on Mac).

**Comment by grvhi** [comment] 2018-08-01 14:51
Interestingly, if I implement similar header mangling (by title-casing alternate characters in the header name for each `set-cookie` header) by over-riding `_wsgi_headers` in a custom Falcon Response class (see: https://github.com/falconry/falcon/blob/master/falcon/response.py#L854), I get multiple `set-cookie` headers in the browser as expected (and the appropriate cookies are set in the browser).

I have confirmed that Falcon sends through multiple `set-cookie` headers, all in lowercase, so I don't think it's Falcon doing something unexpected which cases `serverless-wsgi` not to mangle the headers itself.

**Comment by logandk** [comment] 2018-08-01 21:44
@grvhi It would make sense that you observe a difference in behaviour when running locally vs lambda. This is because cookie header mangling only happens on lambda, whereas the local server is basically just serving the WSGI app using Werkzeug's HTTP server.

Could you set up a simple example application that illustrates the issue? Just a basic Falcon app with corresponding requirements.txt and serverless.yml

**Comment by logandk** [comment] 2018-10-23 19:39
Closing, please reopen if you manage to set up a case for reproducing the issue

**Closed by logandk** 2018-10-23 19:39 UTC
