### ISSUE TITLE
.requirements folder not being created

### ISSUE THREAD

**Issue by zaforic** [logandk/serverless-wsgi#14] opened 2017-04-21 03:00 UTC
I can only get this to work on Centos 7. On any other OS it never creates the .requirements folder.

#As Root
yum install nodejs
yum install npm
npm install -g npm@lts
npm install -g serverless

#Local
mkdir web
cd web/
virtualenv web
source web/bin/activate
pip install flask
npm install --save serverless-wsgi
pip install werkzeug
pip install virtualenv
serverless create --template aws-python
vi serverless.yml
vi requirements.txt (Flask==0.11.1)
vi api.py (same code as readme)
serverless deploy

**Comment by logandk** [comment] 2017-04-21 07:24
The `.requirements` folder is supposed to be created at the beginning of the packaging process and removed during the clean up step. So you should not see the folder once the deployment has completed. Are you getting an error message during `serverless deploy`.

And, if you look inside the final zip package produced by serverless, do you see `.requirements` in there?

**Comment by zaforic** [comment] 2017-04-21 17:00
I am looking in the final zip file and it is missing. Should all of this be ran as root user?

-Richard


________________________________

**Comment by logandk** [comment] 2017-04-27 13:24
It should not be run as root, assuming your user has write access to the serverless service folder.

You could try invoking https://github.com/logandk/serverless-wsgi/blob/master/requirements.py manually:

`python requirements.py requirements.txt .requirements`

This is how it is invoked by serverless, and it should create the `.requirements` directory.

**Comment by logandk** [comment] 2017-05-29 19:57
I'm not able to reproduce this issue and will close it for now. Let me know if this is still a problem.

**Closed by logandk** 2017-05-29 19:57 UTC

**Comment by zaforic** [comment] 2017-05-29 22:28
Sorry it has taken so long to get back. It was working as non-root user but it has now stopped. The .requirements folder is missing from the zip file. When I run "python requirements.py requirements.txt .requirements" from withing the folder "node_modules/serverless-wsgi/" it creates the folder but the folder is empty.

**Comment by zaforic** [comment] 2017-05-29 23:29
The issue appears in amazon linux and not CentOS 7. I am creating a new ticket for amazon linux.
