### ISSUE TITLE
Config file "pwd" not found on remote/local execution

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [logandk/serverless-wsgi#132] opened 2020-03-30 11:25 UTC
Just getting into serverless and currently getting very mysterious errors with some of the `serverless-wsgi` commands. The `sls wsgi serve` works without any issues and I've run a succesfull deployment:

```(FlaskMasterClass) [timsa@DESKTOP-8CC3H71:fmc_app]λ sls wsgi command local -c "pwd"
 
  Error --------------------------------------------------
 
  Error: Config file pwd not found
      at Utils.findServicePath (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:113:15)
      at new Serverless (/usr/local/lib/node_modules/serverless/lib/Serverless.js:42:18)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:76:24
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:489:14)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:489:14)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.11.0
     Framework Version:         1.67.0
     Plugin Version:            3.6.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

Similar error `Error: Config file <passed argument> not found` gets printed with other command types.. for example when executing python:

```
(FlaskMasterClass) [timsa@DESKTOP-8CC3H71:fmc_app]λ sls wsgi exec local -c "print('oopsie')"
 
  Error --------------------------------------------------
 
  Error: Config file print('oopsie') not found
      at Utils.findServicePath (/usr/local/lib/node_modules/serverless/lib/classes/Utils.js:113:15)
      at new Serverless (/usr/local/lib/node_modules/serverless/lib/Serverless.js:42:18)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:76:24
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:489:14)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:489:14)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

Same error happens when attempting to use flask cli commands.
Any pointers on how to move forward? Haven't got remotely (PUN INTENTED) a clue to what to make of those errors.

**Comment by babyhuey** [comment] 2020-04-23 17:57
This is due to a change from serverless using the -c command now. Try doing this with the full command
`sls wsgi exec local --command "print('oopsie')"`

**Comment by logandk** [comment] 2020-05-05 20:38
@babyhuey Thanks for explaining the cause of this, looks like a change of the argument will be needed to avoid the conflict.

**Comment by jpluscplusm** [comment] 2020-09-19 17:47
I just hit this as I started to port a python app to Lambda. As it's my first time using the sls tool, I was following the docs at https://www.serverless.com/plugins/serverless-wsgi to validate that this plugin was installed & happy.

Unfortunately, out of the box, after installing `sls` and then this plugin (via `sls plugin install`) even @babyhuey's long-option-name version doesn't work:

```
$ sls wsgi exec local --command "print('oopsie')"
 
 Exception -----------------------------------------------
 
  'No functions were found with handler: wsgi_handler.handler'
```

Now, I'm confident that this is something I have to fix, and isn't intrinsically sls/serverless-wsgi's "fault" ( ;-) ) but providing some validation steps that work immediately following a vanilla and empty-directory install might be useful for first-timers like myself :-)

**Comment by Warqus** [comment] 2020-12-21 07:59
I ran into the same problem with -c. I switched to --command, but then I get the following error:

```
(project_venv) C:\project>sls wsgi manage --command 'migrate'
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "fr
ameworkVersion: ^2.16.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command wsgi
Serverless: Load command wsgi:serve
Serverless: Load command wsgi:install
Serverless: Load command wsgi:clean
Serverless: Load command wsgi:command
Serverless: Load command wsgi:command:local
Serverless: Load command wsgi:exec
Serverless: Load command wsgi:exec:local
Serverless: Load command wsgi:manage
Serverless: Load command wsgi:manage:local
Serverless: Load command wsgi:flask
Serverless: Load command wsgi:flask:local
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke wsgi:manage

  Error --------------------------------------------------

  Error: Invoked function failed
      at AwsInvoke.log (C:\project\node_modules\serverless\lib\plugins\aws\invoke.js:98:13)
      at Object.invoke:invoke [as hook] (C:\project\node_modules\serverless\lib\plugins\aws\invoke.js:20:
14)
  From previous event:
      at PluginManager.invoke (C:\project\node_modules\serverless\lib\classes\PluginManager.js:521:22)
      at C:\project\node_modules\serverless\lib\classes\PluginManager.js:556:24
  From previous event:
      at PluginManager.run (C:\project\node_modules\serverless\lib\classes\PluginManager.js:556:8)
      at ServerlessWSGI.invokeHandler (C:\project\node_modules\serverless-wsgi\index.js:475:8)
      at ServerlessWSGI.manage (C:\project\node_modules\serverless-wsgi\index.js:540:17)
      at ServerlessWSGI.<anonymous> (C:\project\node_modules\serverless-wsgi\index.js:757:28)
  From previous event:
      at Object.wsgi:manage:manage [as hook] (C:\project\node_modules\serverless-wsgi\index.js:757:12)
      at C:\project\node_modules\serverless\lib\classes\PluginManager.js:521:55
  From previous event:
      at PluginManager.invoke (C:\project\node_modules\serverless\lib\classes\PluginManager.js:521:22)
      at C:\project\node_modules\serverless\lib\classes\PluginManager.js:556:24
  From previous event:
      at PluginManager.run (C:\project\node_modules\serverless\lib\classes\PluginManager.js:556:8)
      at C:\project\node_modules\serverless\lib\Serverless.js:203:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (C:\project\node_modules\serverless\lib\Serverless.js:190:74)
      at C:\project\node_modules\serverless\scripts\serverless.js:50:26

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.14.1
     Framework Version:         2.16.0 (local)
     Plugin Version:            4.3.0
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

How can I fix this?

**Comment by logandk** [comment] 2021-04-25 20:18
Closing in favor of #156.

**Closed by logandk** 2021-04-25 20:18 UTC
Labels: bug
